### ISSUE TITLE
f2fs support

### ISSUE THREAD

**Issue by SantiagoPintos** [agxpro/android_device_xiaomi_whyred#1]
Currently, this twrp can't mount partitions with f2fs file system, kernel seems to be fine (I think) but fstab only supports etx4.

**Comment by agxpro** [comment]
Try older builds for f2fs like official twrp-3.2.3-0 or custom build twrp-3.2.3-1 . F2FS support will come back in future and it's not a twrp problem the issue is related to kernel.

**Comment by SantiagoPintos** [comment]
Oh, I will try, thanks for the info.


________________________________
